language: php
php:
  - 5.5
script:
-  find ./ -name '.git' -prune -o ! -name '.travis.yml' ! -name 'README.md' -mindepth 1 -printf '%P' -type f -exec curl --ftp-create-dirs -T {} -u $FTPUser:$FTPPass ftp://$FTPHost/public_html/{} \;